# Generated by Django 4.2 on 2024-03-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="напишите текст сообщения",
                        verbose_name="текст",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="дата и время создания",
                        null=True,
                        verbose_name="создано",
                    ),
                ),
                (
                    "mail",
                    models.EmailField(
                        help_text="почтовый адрес",
                        max_length=254,
                        verbose_name="e-mail",
                    ),
                ),
            ],
        ),
    ]
