# Generated by Django 4.2 on 2024-03-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="name",
            field=models.CharField(
                default=1,
                help_text="напишите имя",
                max_length=150,
                verbose_name="имя",
            ),
            preserve_default=False,
        ),
    ]
