# Generated by Django 4.2 on 2024-03-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0002_feedback_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="status",
            field=models.CharField(
                choices=[
                    ("получено", "New"),
                    ("в обработке", "Pending"),
                    ("ответ дан", "Complete"),
                ],
                default="получено",
                max_length=11,
                verbose_name="статус",
            ),
        ),
    ]
