# Generated by Django 4.2 on 2024-03-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0005_alter_statuslog_options_statuslog_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statuslog",
            name="_from",
            field=models.CharField(
                choices=[
                    ("получено", "New"),
                    ("в обработке", "Pending"),
                    ("ответ дан", "Complete"),
                ],
                db_column="from",
                max_length=11,
                verbose_name="от",
            ),
        ),
    ]
