# Generated by Django 4.2 on 2024-03-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0006_alter_statuslog__from"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="напишите имя",
                max_length=150,
                null=True,
                verbose_name="имя",
            ),
        ),
    ]
