# Generated by Django 4.2 on 2024-03-11 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0007_alter_feedback_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedbackAuthor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="напишите имя",
                        max_length=150,
                        null=True,
                        verbose_name="имя",
                    ),
                ),
                (
                    "mail",
                    models.EmailField(
                        help_text="почтовый адрес",
                        max_length=254,
                        verbose_name="почта",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="mail",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="name",
        ),
        migrations.CreateModel(
            name="FeedbackFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="")),
                (
                    "feedback",
                    models.ForeignKey(
                        help_text="файлы обратной связи",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        related_query_name="files",
                        to="feedback.feedback",
                        verbose_name="обратная связь",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="feedback",
            name="author",
            field=models.OneToOneField(
                default=5,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback",
                related_query_name="feedback",
                to="feedback.feedbackauthor",
            ),
            preserve_default=False,
        ),
    ]
