# Generated by Django 4.2 on 2024-03-11 14:42

from django.db import migrations, models
import feedback.models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0008_feedbackauthor_remove_feedback_mail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedbackfile",
            name="file",
            field=models.FileField(
                upload_to=feedback.models.FeedbackFile.upload_to
            ),
        ),
    ]
