# Generated by Django 4.2 on 2024-03-11 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0009_alter_feedbackfile_file"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedbackauthor",
            options={
                "verbose_name": "данные автора",
                "verbose_name_plural": "данные авторов",
            },
        ),
        migrations.AlterModelOptions(
            name="feedbackfile",
            options={
                "verbose_name": "файлы обратной связи",
                "verbose_name_plural": "файлы обратных связей",
            },
        ),
        migrations.AlterField(
            model_name="feedbackfile",
            name="feedback",
            field=models.ForeignKey(
                help_text="файлы",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                related_query_name="files",
                to="feedback.feedback",
                verbose_name="обратная связь",
            ),
        ),
    ]
