# Generated by Django 4.2.9 on 2024-03-11 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0011_remove_feedback_author_feedbackauthor_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedbackauthor",
            name="feedback",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author",
                related_query_name="author",
                to="feedback.feedback",
            ),
        ),
    ]
