# Generated by Django 4.2.9 on 2024-03-13 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import feedback.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("feedback", "0012_alter_feedbackauthor_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="status",
            field=models.CharField(
                choices=[
                    ("получено", "New"),
                    ("в обработке", "Pending"),
                    ("ответ дан", "Complete"),
                ],
                default="получено",
                help_text="статус обратной связи",
                max_length=11,
                verbose_name="статус",
            ),
        ),
        migrations.AlterField(
            model_name="feedbackauthor",
            name="feedback",
            field=models.OneToOneField(
                help_text="обратная связь автора",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author",
                related_query_name="author",
                to="feedback.feedback",
                verbose_name="обратная связь",
            ),
        ),
        migrations.AlterField(
            model_name="feedbackfile",
            name="feedback",
            field=models.ForeignKey(
                help_text="обратная связь файла",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                related_query_name="files",
                to="feedback.feedback",
                verbose_name="обратная связь",
            ),
        ),
        migrations.AlterField(
            model_name="feedbackfile",
            name="file",
            field=models.FileField(
                help_text="загрузите файл",
                upload_to=feedback.models.FeedbackFile.upload_to,
                verbose_name="файл",
            ),
        ),
        migrations.AlterField(
            model_name="statuslog",
            name="_from",
            field=models.CharField(
                choices=[
                    ("получено", "New"),
                    ("в обработке", "Pending"),
                    ("ответ дан", "Complete"),
                ],
                db_column="from",
                help_text="изменение статуса с",
                max_length=11,
                verbose_name="с",
            ),
        ),
        migrations.AlterField(
            model_name="statuslog",
            name="feedback",
            field=models.ForeignKey(
                help_text="обратная связь лога",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="feedback.feedback",
                verbose_name="обратная связь",
            ),
        ),
        migrations.AlterField(
            model_name="statuslog",
            name="to",
            field=models.CharField(
                choices=[
                    ("получено", "New"),
                    ("в обработке", "Pending"),
                    ("ответ дан", "Complete"),
                ],
                help_text="изменение статуса на",
                max_length=11,
                verbose_name="на",
            ),
        ),
        migrations.AlterField(
            model_name="statuslog",
            name="user",
            field=models.ForeignKey(
                help_text="пользователь который изменил статус обратной связи",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
