# Generated by Django 4.2.9 on 2024-03-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0014_alter_statuslog_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="statuslog",
            old_name="_from",
            new_name="from_status",
        ),
        migrations.AlterField(
            model_name="statuslog",
            name="to",
            field=models.CharField(
                choices=[
                    ("получено", "New"),
                    ("в обработке", "Pending"),
                    ("ответ дан", "Complete"),
                ],
                db_column="to",
                help_text="изменение статуса на",
                max_length=11,
                verbose_name="на",
            ),
        ),
        migrations.RenameField(
            model_name="statuslog",
            old_name="to",
            new_name="to_status",
        ),
    ]
