# Generated by Django 4.2.9 on 2024-03-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0015_rename__from_statuslog_from_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="text",
            field=models.TextField(
                help_text="напишите текст сообщения",
                max_length=4000,
                verbose_name="текст",
            ),
        ),
    ]
