# Generated by Django 4.2.9 on 2024-03-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0016_alter_feedback_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="status",
            field=models.CharField(
                choices=[
                    ("NW", "new_status"),
                    ("PD", "pending_status"),
                    ("CP", "complete_status"),
                ],
                default="NW",
                help_text="статус обратной связи",
                max_length=11,
                verbose_name="статус",
            ),
        ),
        migrations.AlterField(
            model_name="statuslog",
            name="from_status",
            field=models.CharField(
                choices=[
                    ("NW", "new_status"),
                    ("PD", "pending_status"),
                    ("CP", "complete_status"),
                ],
                db_column="from",
                help_text="изменение статуса с",
                max_length=11,
                verbose_name="с",
            ),
        ),
        migrations.AlterField(
            model_name="statuslog",
            name="to_status",
            field=models.CharField(
                choices=[
                    ("NW", "new_status"),
                    ("PD", "pending_status"),
                    ("CP", "complete_status"),
                ],
                db_column="to",
                help_text="изменение статуса на",
                max_length=11,
                verbose_name="на",
            ),
        ),
    ]
