# Generated by Django 4.2.9 on 2024-04-08 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "feedback",
            "0018_alter_feedback_status_alter_statuslog_from_status_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedbackauthor",
            name="name",
        ),
    ]
