# Generated by Django 4.2.9 on 2024-04-11 16:45

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ("streetsport", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="game",
            options={"verbose_name": "game", "verbose_name_plural": "games"},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "order", "verbose_name_plural": "orders"},
        ),
        migrations.AddField(
            model_name="order",
            name="start",
            field=models.DateTimeField(
                blank=True,
                help_text="start_field_help",
                null=True,
                validators=[users.validators.birthday_validator],
                verbose_name="start",
            ),
        ),
    ]
