# Generated by Django 4.2.9 on 2024-04-11 16:53

from django.db import migrations, models
import streetsport.validators


class Migration(migrations.Migration):

    dependencies = [
        (
            "streetsport",
            "0002_alter_game_options_alter_order_options_order_start",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="start",
            field=models.DateTimeField(
                blank=True,
                help_text="start_field_help",
                null=True,
                validators=[streetsport.validators.start_validator],
                verbose_name="start",
            ),
        ),
    ]
