# Generated by Django 4.2.9 on 2024-04-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streetsport", "0003_alter_order_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="rating",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="rating_field_help", verbose_name="rating"
            ),
        ),
    ]
