# Generated by Django 4.2.9 on 2024-04-14 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("streetsport", "0004_alter_team_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="game",
            field=models.ForeignKey(
                help_text="order_game_help_text",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_game",
                related_query_name="order_game",
                to="streetsport.game",
                verbose_name="order_game",
            ),
        ),
    ]
