# Generated by Django 4.2.9 on 2024-04-07 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="user",
            field=models.ForeignKey(
                default=1,
                help_text="user_field_help",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                related_query_name="images",
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователь",
            ),
            preserve_default=False,
        ),
    ]
