# Generated by Django 4.2.9 on 2024-04-08 15:14

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="inst_link",
            field=models.CharField(
                blank=True,
                help_text="inst_link_field_help",
                max_length=269,
                null=True,
                validators=[users.validators.inst_link_validator],
                verbose_name="inst_link",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="tg_link",
            field=models.CharField(
                blank=True,
                help_text="tg_link_field_help",
                max_length=44,
                null=True,
                validators=[users.validators.tg_link_validator],
                verbose_name="tg_link",
            ),
        ),
    ]
