# Generated by Django 4.2.9 on 2024-04-12 17:01

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="user",
            field=models.ForeignKey(
                help_text="user_field_help",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                related_query_name="images",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="inst_link",
            field=models.CharField(
                blank=True,
                help_text="inst_link_field_help",
                max_length=269,
                null=True,
                validators=[],
                verbose_name="inst_link",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="tg_link",
            field=models.CharField(
                blank=True,
                help_text="tg_link_field_help",
                max_length=44,
                null=True,
                validators=[users.validators.TgLinkValidator],
                verbose_name="tg_link",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={
                    "unique": "A user with that username already exists."
                },
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=150,
                unique=True,
                validators=[
                    django.contrib.auth.validators.UnicodeUsernameValidator()
                ],
                verbose_name="username",
            ),
        ),
    ]
