# Generated by Django 4.2.9 on 2024-04-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_image_user_alter_user_inst_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="rating",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="rating_field_help", verbose_name="rating"
            ),
        ),
    ]
