# Generated by Django 4.2.9 on 2024-04-13 19:20

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_user_inst_link_alter_user_tg_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={
                    "unique": "A user with that username already exists."
                },
                help_text="username_field_help",
                max_length=32,
                unique=True,
                validators=[users.validators.UsernameValidator()],
                verbose_name="username",
            ),
        ),
    ]
