# Generated by Django 4.2.9 on 2024-04-16 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_auto_20240413_2026"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["rating"],
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
    ]
