# Generated by Django 4.2.9 on 2024-04-21 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("streetsport", "0011_remove_team_lead_remove_team_teammates"),
        ("users", "0010_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="lead_team",
            field=models.OneToOneField(
                blank=True,
                help_text="lead__team_field_help",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lead",
                related_query_name="lead",
                to="streetsport.team",
                verbose_name="lead_team",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="team",
            field=models.ForeignKey(
                blank=True,
                help_text="team_field_help",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teammates",
                related_query_name="teammates",
                to="streetsport.team",
                verbose_name="team",
            ),
        ),
    ]
