# Generated by Django 4.2.9 on 2024-04-24 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_user_lead_team_user_team"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["rating", "username"],
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
    ]
